import Head from 'next/head'
import TournamentView from '../../../../components/tournament-view';

export default function Home() {
  return (
    <>
      <Head>
        <title>Liga SJN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TournamentView />
      </main>
    </>
  )
}
